name: Android Kernel Build

on:
  workflow_dispatch:
  push:
    branches:
      - action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - shell: bash
      name: Add Remote Credentials
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        echo -e "\nBOT_TOKEN=$BOT_TOKEN" >> local.config

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git-core libncurses5-dev libssl-dev lolcat toilet python2

        bash <(curl https://gist.githubusercontent.com/roynatech2544/0feeeb35a6d1782b186990ff2a0b3657/raw/a46f5b3901a750c8877d19ac1e63569783b7e237/setup.sh)

    - name: Build kernel
      run: |
        ./build_kernel.sh
